### ISSUE TITLE
Traefik config no longer valid

### ISSUE THREAD

**Issue by samip5** [Kerwood/the-pirate-cove#1]
Traefik version 2.2

Your configuration is no longer valid, and you should configure it though files so it's much simpler to understand. Cannot get HTTPS working.

**Comment by Kerwood** [comment]
I usually avoid using a config file for traefik in minor simple setups like this. It makes things easier to handle.
Yes, configuration is invalid for Traefik v.2+.
I will fix that with a v1.7 version tag.

**Comment by samip5** [comment]
I wouldn't call that a fix. Set the config correctly for v2+ and then I would say it's fixed.

**Comment by Kerwood** [comment]
You can call it what ever the fuck you want.

**Comment by samip5** [comment]
No need to sound that aggressive, I was just pointing it out that it would be good to use the v2+ version.

**Comment by Kerwood** [comment]
Traefik v1.7 is supported until the end of 2021. PR's are welcome.
